### ISSUE TITLE
cmake error 

### ISSUE THREAD

**Issue by Qingluan** [knivey/google#1]
`CMake Error at CMakeLists.txt:5 (add_subdirectory):
  The source directory

```
/Users/xxx/xxx/google/jansson
```

  does not contain a CMakeLists.txt file.

`
*_i use osx *_

**Comment by knivey** [comment]
Sorry, looks like I didn't setup the jansson submodule correctly. I've updated the readme with new instructions for building, however the search currently isn't working due to the google API it used being removed.
